ifneq ($(findstring __TOUCH_GH61X__,$(KBUILD_CPPFLAGS)), )
obj-y += gh61x/ 
endif

ifneq ($(findstring __TOUCH_GH621X__,$(KBUILD_CPPFLAGS)), )
obj-y += gh6212_code/ 
endif

ifneq ($(findstring __TOUCH_SIMULATION__,$(KBUILD_CPPFLAGS)), )
obj-y += touch_simu/
endif
