ifneq ($(findstring __PRESSURE_AW8680X__,$(KBUILD_CPPFLAGS)), )
obj-y += aw8680x/
endif

ifneq ($(findstring __PRESSURE_CSA37F71__,$(KBUILD_CPPFLAGS)), )
obj-y += csa37f71/
endif

ifneq ($(findstring __PRESSURE_NEXTINPUT__,$(KBUILD_CPPFLAGS)), )
obj-y += nextinput/
endif
