ifeq ($(XSPACE_BATTERY_MANAGER),1)
obj-y += xspace_battery_manager/
endif

ifeq ($(XSPACE_COVER_SWITCH_MANAGER),1)
obj-y += xspace_cover_switch_manager/
endif

ifeq ($(XSPACE_GESTURE_MANAGER),1)
obj-y += xspace_gesture_manager/
endif

ifeq ($(XSPACE_INEAR_DETECTION_MANAGER),1)
obj-y += xspace_inear_detect_manager/
endif

ifeq ($(XSPACE_INOUT_BOX_MANAGER),1)
obj-y += xspace_inout_box_manager/
endif

ifeq ($(XSPACE_XBUS_MANAGER),1)
obj-y += xspace_xbus_manager/
endif
