/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dma.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dma.pb-c.h"
void   dma_control_envelope__init
                     (ControlEnvelope         *message)
{
  static const ControlEnvelope init_value = CONTROL_ENVELOPE__INIT;
  *message = init_value;
}
size_t dma_control_envelope__get_packed_size
                     (const ControlEnvelope *message)
{
  assert(message->base.descriptor == &dma_control_envelope__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_control_envelope__pack
                     (const ControlEnvelope *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_control_envelope__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_control_envelope__pack_to_buffer
                     (const ControlEnvelope *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_control_envelope__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ControlEnvelope *
       dma_control_envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ControlEnvelope *)
     protobuf_c_message_unpack (&dma_control_envelope__descriptor,
                                allocator, len, data);
}
void   dma_control_envelope__free_unpacked
                     (ControlEnvelope *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_control_envelope__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t dma_response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &dma_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       dma_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&dma_response__descriptor,
                                allocator, len, data);
}
void   dma_response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_dialog__init
                     (Dialog         *message)
{
  static const Dialog init_value = DIALOG__INIT;
  *message = init_value;
}
size_t dma_dialog__get_packed_size
                     (const Dialog *message)
{
  assert(message->base.descriptor == &dma_dialog__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_dialog__pack
                     (const Dialog *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_dialog__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_dialog__pack_to_buffer
                     (const Dialog *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_dialog__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dialog *
       dma_dialog__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dialog *)
     protobuf_c_message_unpack (&dma_dialog__descriptor,
                                allocator, len, data);
}
void   dma_dialog__free_unpacked
                     (Dialog *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_dialog__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_speech_initiator__wake_word__init
                     (SpeechInitiator__WakeWord         *message)
{
  static const SpeechInitiator__WakeWord init_value = SPEECH_INITIATOR__WAKE_WORD__INIT;
  *message = init_value;
}
void   dma_speech_initiator__init
                     (SpeechInitiator         *message)
{
  static const SpeechInitiator init_value = SPEECH_INITIATOR__INIT;
  *message = init_value;
}
size_t dma_speech_initiator__get_packed_size
                     (const SpeechInitiator *message)
{
  assert(message->base.descriptor == &dma_speech_initiator__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_speech_initiator__pack
                     (const SpeechInitiator *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_speech_initiator__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_speech_initiator__pack_to_buffer
                     (const SpeechInitiator *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_speech_initiator__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpeechInitiator *
       dma_speech_initiator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpeechInitiator *)
     protobuf_c_message_unpack (&dma_speech_initiator__descriptor,
                                allocator, len, data);
}
void   dma_speech_initiator__free_unpacked
                     (SpeechInitiator *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_speech_initiator__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_speech_settings__init
                     (SpeechSettings         *message)
{
  static const SpeechSettings init_value = SPEECH_SETTINGS__INIT;
  *message = init_value;
}
size_t dma_speech_settings__get_packed_size
                     (const SpeechSettings *message)
{
  assert(message->base.descriptor == &dma_speech_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_speech_settings__pack
                     (const SpeechSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_speech_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_speech_settings__pack_to_buffer
                     (const SpeechSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_speech_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpeechSettings *
       dma_speech_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpeechSettings *)
     protobuf_c_message_unpack (&dma_speech_settings__descriptor,
                                allocator, len, data);
}
void   dma_speech_settings__free_unpacked
                     (SpeechSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_speech_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_start_speech__init
                     (StartSpeech         *message)
{
  static const StartSpeech init_value = START_SPEECH__INIT;
  *message = init_value;
}
size_t dma_start_speech__get_packed_size
                     (const StartSpeech *message)
{
  assert(message->base.descriptor == &dma_start_speech__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_start_speech__pack
                     (const StartSpeech *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_start_speech__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_start_speech__pack_to_buffer
                     (const StartSpeech *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_start_speech__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartSpeech *
       dma_start_speech__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartSpeech *)
     protobuf_c_message_unpack (&dma_start_speech__descriptor,
                                allocator, len, data);
}
void   dma_start_speech__free_unpacked
                     (StartSpeech *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_start_speech__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_provide_speech__init
                     (ProvideSpeech         *message)
{
  static const ProvideSpeech init_value = PROVIDE_SPEECH__INIT;
  *message = init_value;
}
size_t dma_provide_speech__get_packed_size
                     (const ProvideSpeech *message)
{
  assert(message->base.descriptor == &dma_provide_speech__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_provide_speech__pack
                     (const ProvideSpeech *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_provide_speech__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_provide_speech__pack_to_buffer
                     (const ProvideSpeech *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_provide_speech__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProvideSpeech *
       dma_provide_speech__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProvideSpeech *)
     protobuf_c_message_unpack (&dma_provide_speech__descriptor,
                                allocator, len, data);
}
void   dma_provide_speech__free_unpacked
                     (ProvideSpeech *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_provide_speech__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_speech_provider__init
                     (SpeechProvider         *message)
{
  static const SpeechProvider init_value = SPEECH_PROVIDER__INIT;
  *message = init_value;
}
size_t dma_speech_provider__get_packed_size
                     (const SpeechProvider *message)
{
  assert(message->base.descriptor == &dma_speech_provider__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_speech_provider__pack
                     (const SpeechProvider *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_speech_provider__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_speech_provider__pack_to_buffer
                     (const SpeechProvider *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_speech_provider__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpeechProvider *
       dma_speech_provider__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpeechProvider *)
     protobuf_c_message_unpack (&dma_speech_provider__descriptor,
                                allocator, len, data);
}
void   dma_speech_provider__free_unpacked
                     (SpeechProvider *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_speech_provider__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_stop_speech__init
                     (StopSpeech         *message)
{
  static const StopSpeech init_value = STOP_SPEECH__INIT;
  *message = init_value;
}
size_t dma_stop_speech__get_packed_size
                     (const StopSpeech *message)
{
  assert(message->base.descriptor == &dma_stop_speech__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_stop_speech__pack
                     (const StopSpeech *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_stop_speech__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_stop_speech__pack_to_buffer
                     (const StopSpeech *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_stop_speech__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StopSpeech *
       dma_stop_speech__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StopSpeech *)
     protobuf_c_message_unpack (&dma_stop_speech__descriptor,
                                allocator, len, data);
}
void   dma_stop_speech__free_unpacked
                     (StopSpeech *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_stop_speech__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_point_speech__init
                     (EndPointSpeech         *message)
{
  static const EndPointSpeech init_value = END_POINT_SPEECH__INIT;
  *message = init_value;
}
size_t end_point_speech__get_packed_size
                     (const EndPointSpeech *message)
{
  assert(message->base.descriptor == &end_point_speech__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_point_speech__pack
                     (const EndPointSpeech *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_point_speech__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_point_speech__pack_to_buffer
                     (const EndPointSpeech *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_point_speech__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndPointSpeech *
       end_point_speech__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndPointSpeech *)
     protobuf_c_message_unpack (&end_point_speech__descriptor,
                                allocator, len, data);
}
void   end_point_speech__free_unpacked
                     (EndPointSpeech *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_point_speech__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_notify_speech_state__init
                     (NotifySpeechState         *message)
{
  static const NotifySpeechState init_value = NOTIFY_SPEECH_STATE__INIT;
  *message = init_value;
}
size_t dma_notify_speech_state__get_packed_size
                     (const NotifySpeechState *message)
{
  assert(message->base.descriptor == &dma_notify_speech_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_notify_speech_state__pack
                     (const NotifySpeechState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_notify_speech_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_notify_speech_state__pack_to_buffer
                     (const NotifySpeechState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_notify_speech_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifySpeechState *
       dma_notify_speech_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifySpeechState *)
     protobuf_c_message_unpack (&dma_notify_speech_state__descriptor,
                                allocator, len, data);
}
void   dma_notify_speech_state__free_unpacked
                     (NotifySpeechState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_notify_speech_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_device_information__init
                     (DeviceInformation         *message)
{
  static const DeviceInformation init_value = DEVICE_INFORMATION__INIT;
  *message = init_value;
}
size_t dma_device_information__get_packed_size
                     (const DeviceInformation *message)
{
  assert(message->base.descriptor == &dma_device_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_device_information__pack
                     (const DeviceInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_device_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_device_information__pack_to_buffer
                     (const DeviceInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_device_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInformation *
       dma_device_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInformation *)
     protobuf_c_message_unpack (&dma_device_information__descriptor,
                                allocator, len, data);
}
void   dma_device_information__free_unpacked
                     (DeviceInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_device_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pair_information__init
                     (PairInformation         *message)
{
  static const PairInformation init_value = PAIR_INFORMATION__INIT;
  *message = init_value;
}
size_t pair_information__get_packed_size
                     (const PairInformation *message)
{
  assert(message->base.descriptor == &pair_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pair_information__pack
                     (const PairInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pair_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pair_information__pack_to_buffer
                     (const PairInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pair_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PairInformation *
       pair_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PairInformation *)
     protobuf_c_message_unpack (&pair_information__descriptor,
                                allocator, len, data);
}
void   pair_information__free_unpacked
                     (PairInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pair_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_device_configuration__init
                     (DeviceConfiguration         *message)
{
  static const DeviceConfiguration init_value = DEVICE_CONFIGURATION__INIT;
  *message = init_value;
}
size_t dma_device_configuration__get_packed_size
                     (const DeviceConfiguration *message)
{
  assert(message->base.descriptor == &dma_device_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_device_configuration__pack
                     (const DeviceConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_device_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_device_configuration__pack_to_buffer
                     (const DeviceConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_device_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceConfiguration *
       dma_device_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceConfiguration *)
     protobuf_c_message_unpack (&dma_device_configuration__descriptor,
                                allocator, len, data);
}
void   dma_device_configuration__free_unpacked
                     (DeviceConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_device_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_get_device_information__init
                     (GetDeviceInformation         *message)
{
  static const GetDeviceInformation init_value = GET_DEVICE_INFORMATION__INIT;
  *message = init_value;
}
size_t dma_get_device_information__get_packed_size
                     (const GetDeviceInformation *message)
{
  assert(message->base.descriptor == &dma_get_device_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_get_device_information__pack
                     (const GetDeviceInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_get_device_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_get_device_information__pack_to_buffer
                     (const GetDeviceInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_get_device_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetDeviceInformation *
       dma_get_device_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetDeviceInformation *)
     protobuf_c_message_unpack (&dma_get_device_information__descriptor,
                                allocator, len, data);
}
void   dma_get_device_information__free_unpacked
                     (GetDeviceInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_get_device_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_get_device_configuration__init
                     (GetDeviceConfiguration         *message)
{
  static const GetDeviceConfiguration init_value = GET_DEVICE_CONFIGURATION__INIT;
  *message = init_value;
}
size_t dma_get_device_configuration__get_packed_size
                     (const GetDeviceConfiguration *message)
{
  assert(message->base.descriptor == &dma_get_device_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_get_device_configuration__pack
                     (const GetDeviceConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_get_device_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_get_device_configuration__pack_to_buffer
                     (const GetDeviceConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_get_device_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetDeviceConfiguration *
       dma_get_device_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetDeviceConfiguration *)
     protobuf_c_message_unpack (&dma_get_device_configuration__descriptor,
                                allocator, len, data);
}
void   dma_get_device_configuration__free_unpacked
                     (GetDeviceConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_get_device_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_notify_device_configuration__init
                     (NotifyDeviceConfiguration         *message)
{
  static const NotifyDeviceConfiguration init_value = NOTIFY_DEVICE_CONFIGURATION__INIT;
  *message = init_value;
}
size_t dma_notify_device_configuration__get_packed_size
                     (const NotifyDeviceConfiguration *message)
{
  assert(message->base.descriptor == &dma_notify_device_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_notify_device_configuration__pack
                     (const NotifyDeviceConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_notify_device_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_notify_device_configuration__pack_to_buffer
                     (const NotifyDeviceConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_notify_device_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyDeviceConfiguration *
       dma_notify_device_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyDeviceConfiguration *)
     protobuf_c_message_unpack (&dma_notify_device_configuration__descriptor,
                                allocator, len, data);
}
void   dma_notify_device_configuration__free_unpacked
                     (NotifyDeviceConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_notify_device_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_state__init
                     (State         *message)
{
  static const State init_value = STATE__INIT;
  *message = init_value;
}
size_t dma_state__get_packed_size
                     (const State *message)
{
  assert(message->base.descriptor == &dma_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_state__pack
                     (const State *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_state__pack_to_buffer
                     (const State *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State *
       dma_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State *)
     protobuf_c_message_unpack (&dma_state__descriptor,
                                allocator, len, data);
}
void   dma_state__free_unpacked
                     (State *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_get_state__init
                     (GetState         *message)
{
  static const GetState init_value = GET_STATE__INIT;
  *message = init_value;
}
size_t dma_get_state__get_packed_size
                     (const GetState *message)
{
  assert(message->base.descriptor == &dma_get_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_get_state__pack
                     (const GetState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_get_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_get_state__pack_to_buffer
                     (const GetState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_get_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetState *
       dma_get_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetState *)
     protobuf_c_message_unpack (&dma_get_state__descriptor,
                                allocator, len, data);
}
void   dma_get_state__free_unpacked
                     (GetState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_get_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_set_state__init
                     (SetState         *message)
{
  static const SetState init_value = SET_STATE__INIT;
  *message = init_value;
}
size_t dma_set_state__get_packed_size
                     (const SetState *message)
{
  assert(message->base.descriptor == &dma_set_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_set_state__pack
                     (const SetState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_set_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_set_state__pack_to_buffer
                     (const SetState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_set_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetState *
       dma_set_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetState *)
     protobuf_c_message_unpack (&dma_set_state__descriptor,
                                allocator, len, data);
}
void   dma_set_state__free_unpacked
                     (SetState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_set_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_synchronize_state__init
                     (SynchronizeState         *message)
{
  static const SynchronizeState init_value = SYNCHRONIZE_STATE__INIT;
  *message = init_value;
}
size_t dma_synchronize_state__get_packed_size
                     (const SynchronizeState *message)
{
  assert(message->base.descriptor == &dma_synchronize_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_synchronize_state__pack
                     (const SynchronizeState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_synchronize_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_synchronize_state__pack_to_buffer
                     (const SynchronizeState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_synchronize_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SynchronizeState *
       dma_synchronize_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SynchronizeState *)
     protobuf_c_message_unpack (&dma_synchronize_state__descriptor,
                                allocator, len, data);
}
void   dma_synchronize_state__free_unpacked
                     (SynchronizeState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_synchronize_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_forward_atcommand__init
                     (ForwardATCommand         *message)
{
  static const ForwardATCommand init_value = FORWARD_ATCOMMAND__INIT;
  *message = init_value;
}
size_t dma_forward_atcommand__get_packed_size
                     (const ForwardATCommand *message)
{
  assert(message->base.descriptor == &dma_forward_atcommand__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_forward_atcommand__pack
                     (const ForwardATCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_forward_atcommand__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_forward_atcommand__pack_to_buffer
                     (const ForwardATCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_forward_atcommand__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ForwardATCommand *
       dma_forward_atcommand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ForwardATCommand *)
     protobuf_c_message_unpack (&dma_forward_atcommand__descriptor,
                                allocator, len, data);
}
void   dma_forward_atcommand__free_unpacked
                     (ForwardATCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_forward_atcommand__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   forward_test_command__init
                     (ForwardTestCommand         *message)
{
  static const ForwardTestCommand init_value = FORWARD_TEST_COMMAND__INIT;
  *message = init_value;
}
size_t forward_test_command__get_packed_size
                     (const ForwardTestCommand *message)
{
  assert(message->base.descriptor == &forward_test_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t forward_test_command__pack
                     (const ForwardTestCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &forward_test_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t forward_test_command__pack_to_buffer
                     (const ForwardTestCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &forward_test_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ForwardTestCommand *
       forward_test_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ForwardTestCommand *)
     protobuf_c_message_unpack (&forward_test_command__descriptor,
                                allocator, len, data);
}
void   forward_test_command__free_unpacked
                     (ForwardTestCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &forward_test_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dma_issue_media_control__init
                     (IssueMediaControl         *message)
{
  static const IssueMediaControl init_value = ISSUE_MEDIA_CONTROL__INIT;
  *message = init_value;
}
size_t dma_issue_media_control__get_packed_size
                     (const IssueMediaControl *message)
{
  assert(message->base.descriptor == &dma_issue_media_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dma_issue_media_control__pack
                     (const IssueMediaControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dma_issue_media_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dma_issue_media_control__pack_to_buffer
                     (const IssueMediaControl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dma_issue_media_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IssueMediaControl *
       dma_issue_media_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IssueMediaControl *)
     protobuf_c_message_unpack (&dma_issue_media_control__descriptor,
                                allocator, len, data);
}
void   dma_issue_media_control__free_unpacked
                     (IssueMediaControl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dma_issue_media_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor control_envelope__field_descriptors[19] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ControlEnvelope, command),
    &dma_command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControlEnvelope, request_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign2",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControlEnvelope, sign2),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rand2",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControlEnvelope, rand2),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, response),
    &dma_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "provideSpeech",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, providespeech),
    &dma_provide_speech__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startSpeech",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, startspeech),
    &dma_start_speech__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stopSpeech",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, stopspeech),
    &dma_stop_speech__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endPointSpeech",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, endpointspeech),
    &end_point_speech__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notifySpeechState",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, notifyspeechstate),
    &dma_notify_speech_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getDeviceInformation",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, getdeviceinformation),
    &dma_get_device_information__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getDeviceConfiguration",
    27,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, getdeviceconfiguration),
    &dma_get_device_configuration__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notifyDeviceConfiguration",
    28,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, notifydeviceconfiguration),
    &dma_notify_device_configuration__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getState",
    29,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, getstate),
    &dma_get_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setState",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, setstate),
    &dma_set_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "synchronizeState",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, synchronizestate),
    &dma_synchronize_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forwardATCommand",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, forwardatcommand),
    &dma_forward_atcommand__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forwardTestCommand",
    33,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, forwardtestcommand),
    &forward_test_command__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "issue_media_control",
    34,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ControlEnvelope, payload_case),
    offsetof(ControlEnvelope, issue_media_control),
    &dma_issue_media_control__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned control_envelope__field_indices_by_name[] = {
  0,   /* field[0] = command */
  8,   /* field[8] = endPointSpeech */
  16,   /* field[16] = forwardATCommand */
  17,   /* field[17] = forwardTestCommand */
  11,   /* field[11] = getDeviceConfiguration */
  10,   /* field[10] = getDeviceInformation */
  13,   /* field[13] = getState */
  18,   /* field[18] = issue_media_control */
  12,   /* field[12] = notifyDeviceConfiguration */
  9,   /* field[9] = notifySpeechState */
  5,   /* field[5] = provideSpeech */
  3,   /* field[3] = rand2 */
  1,   /* field[1] = request_id */
  4,   /* field[4] = response */
  14,   /* field[14] = setState */
  2,   /* field[2] = sign2 */
  6,   /* field[6] = startSpeech */
  7,   /* field[7] = stopSpeech */
  15,   /* field[15] = synchronizeState */
};
static const ProtobufCIntRange control_envelope__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 9, 4 },
  { 21, 5 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor dma_control_envelope__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ControlEnvelope",
  "ControlEnvelope",
  "ControlEnvelope",
  "",
  sizeof(ControlEnvelope),
  19,
  control_envelope__field_descriptors,
  control_envelope__field_indices_by_name,
  3,  control_envelope__number_ranges,
  (ProtobufCMessageInit) dma_control_envelope__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[6] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, error_code),
    &dma_error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speechProvider",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, payload_case),
    offsetof(Response, speechprovider),
    &dma_speech_provider__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceInformation",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, payload_case),
    offsetof(Response, deviceinformation),
    &dma_device_information__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceConfiguration",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, payload_case),
    offsetof(Response, deviceconfiguration),
    &dma_device_configuration__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, payload_case),
    offsetof(Response, state),
    &dma_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairInformation",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, payload_case),
    offsetof(Response, pairinformation),
    &pair_information__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  3,   /* field[3] = deviceConfiguration */
  2,   /* field[2] = deviceInformation */
  0,   /* field[0] = error_code */
  5,   /* field[5] = pairInformation */
  1,   /* field[1] = speechProvider */
  4,   /* field[4] = state */
};
static const ProtobufCIntRange response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 1 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor dma_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  6,
  response__field_descriptors,
  response__field_indices_by_name,
  2,  response__number_ranges,
  (ProtobufCMessageInit) dma_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dialog__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dialog, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dialog__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange dialog__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dma_dialog__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Dialog",
  "Dialog",
  "Dialog",
  "",
  sizeof(Dialog),
  1,
  dialog__field_descriptors,
  dialog__field_indices_by_name,
  1,  dialog__number_ranges,
  (ProtobufCMessageInit) dma_dialog__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech_initiator__wake_word__field_descriptors[2] =
{
  {
    "start_index_in_samples",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator__WakeWord, start_index_in_samples),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_index_in_samples",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator__WakeWord, end_index_in_samples),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech_initiator__wake_word__field_indices_by_name[] = {
  1,   /* field[1] = end_index_in_samples */
  0,   /* field[0] = start_index_in_samples */
};
static const ProtobufCIntRange speech_initiator__wake_word__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dma_speech_initiator__wake_word__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeechInitiator.WakeWord",
  "WakeWord",
  "SpeechInitiator__WakeWord",
  "",
  sizeof(SpeechInitiator__WakeWord),
  2,
  speech_initiator__wake_word__field_descriptors,
  speech_initiator__wake_word__field_indices_by_name,
  1,  speech_initiator__wake_word__number_ranges,
  (ProtobufCMessageInit) dma_speech_initiator__wake_word__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue speech_initiator__type__enum_values_by_number[4] =
{
  { "NONE", "SPEECH_INITIATOR__TYPE__NONE", 0 },
  { "PRESS_AND_HOLD", "SPEECH_INITIATOR__TYPE__PRESS_AND_HOLD", 1 },
  { "TAP", "SPEECH_INITIATOR__TYPE__TAP", 3 },
  { "WAKEWORD", "SPEECH_INITIATOR__TYPE__WAKEWORD", 4 },
};
static const ProtobufCIntRange speech_initiator__type__value_ranges[] = {
{0, 0},{3, 2},{0, 4}
};
static const ProtobufCEnumValueIndex speech_initiator__type__enum_values_by_name[4] =
{
  { "NONE", 0 },
  { "PRESS_AND_HOLD", 1 },
  { "TAP", 2 },
  { "WAKEWORD", 3 },
};
const ProtobufCEnumDescriptor dma_speech_initiator__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SpeechInitiator.Type",
  "Type",
  "SpeechInitiator__Type",
  "",
  4,
  speech_initiator__type__enum_values_by_number,
  4,
  speech_initiator__type__enum_values_by_name,
  2,
  speech_initiator__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor speech_initiator__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator, type),
    &dma_speech_initiator__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wake_word",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator, wake_word),
    &dma_speech_initiator__wake_word__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "play_prompt_tone",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator, play_prompt_tone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech_initiator__field_indices_by_name[] = {
  2,   /* field[2] = play_prompt_tone */
  0,   /* field[0] = type */
  1,   /* field[1] = wake_word */
};
static const ProtobufCIntRange speech_initiator__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dma_speech_initiator__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeechInitiator",
  "SpeechInitiator",
  "SpeechInitiator",
  "",
  sizeof(SpeechInitiator),
  3,
  speech_initiator__field_descriptors,
  speech_initiator__field_indices_by_name,
  1,  speech_initiator__number_ranges,
  (ProtobufCMessageInit) dma_speech_initiator__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech_settings__field_descriptors[3] =
{
  {
    "audio_profile",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SpeechSettings, audio_profile),
    &dma_audio_profile__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio_format",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SpeechSettings, audio_format),
    &dma_audio_format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio_source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SpeechSettings, audio_source),
    &dma_audio_source__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech_settings__field_indices_by_name[] = {
  1,   /* field[1] = audio_format */
  0,   /* field[0] = audio_profile */
  2,   /* field[2] = audio_source */
};
static const ProtobufCIntRange speech_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dma_speech_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeechSettings",
  "SpeechSettings",
  "SpeechSettings",
  "",
  sizeof(SpeechSettings),
  3,
  speech_settings__field_descriptors,
  speech_settings__field_indices_by_name,
  1,  speech_settings__number_ranges,
  (ProtobufCMessageInit) dma_speech_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_speech__field_descriptors[3] =
{
  {
    "settings",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartSpeech, settings),
    &dma_speech_settings__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initiator",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartSpeech, initiator),
    &dma_speech_initiator__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dialog",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartSpeech, dialog),
    &dma_dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_speech__field_indices_by_name[] = {
  2,   /* field[2] = dialog */
  1,   /* field[1] = initiator */
  0,   /* field[0] = settings */
};
static const ProtobufCIntRange start_speech__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dma_start_speech__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartSpeech",
  "StartSpeech",
  "StartSpeech",
  "",
  sizeof(StartSpeech),
  3,
  start_speech__field_descriptors,
  start_speech__field_indices_by_name,
  1,  start_speech__number_ranges,
  (ProtobufCMessageInit) dma_start_speech__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor provide_speech__field_descriptors[1] =
{
  {
    "dialog",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProvideSpeech, dialog),
    &dma_dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned provide_speech__field_indices_by_name[] = {
  0,   /* field[0] = dialog */
};
static const ProtobufCIntRange provide_speech__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dma_provide_speech__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProvideSpeech",
  "ProvideSpeech",
  "ProvideSpeech",
  "",
  sizeof(ProvideSpeech),
  1,
  provide_speech__field_descriptors,
  provide_speech__field_indices_by_name,
  1,  provide_speech__number_ranges,
  (ProtobufCMessageInit) dma_provide_speech__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech_provider__field_descriptors[2] =
{
  {
    "settings",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SpeechProvider, settings),
    &dma_speech_settings__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dialog",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SpeechProvider, dialog),
    &dma_dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech_provider__field_indices_by_name[] = {
  1,   /* field[1] = dialog */
  0,   /* field[0] = settings */
};
static const ProtobufCIntRange speech_provider__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dma_speech_provider__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeechProvider",
  "SpeechProvider",
  "SpeechProvider",
  "",
  sizeof(SpeechProvider),
  2,
  speech_provider__field_descriptors,
  speech_provider__field_indices_by_name,
  1,  speech_provider__number_ranges,
  (ProtobufCMessageInit) dma_speech_provider__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stop_speech__field_descriptors[2] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StopSpeech, error_code),
    &dma_error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dialog",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StopSpeech, dialog),
    &dma_dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stop_speech__field_indices_by_name[] = {
  1,   /* field[1] = dialog */
  0,   /* field[0] = error_code */
};
static const ProtobufCIntRange stop_speech__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dma_stop_speech__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StopSpeech",
  "StopSpeech",
  "StopSpeech",
  "",
  sizeof(StopSpeech),
  2,
  stop_speech__field_descriptors,
  stop_speech__field_indices_by_name,
  1,  stop_speech__number_ranges,
  (ProtobufCMessageInit) dma_stop_speech__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_point_speech__field_descriptors[1] =
{
  {
    "dialog",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EndPointSpeech, dialog),
    &dma_dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_point_speech__field_indices_by_name[] = {
  0,   /* field[0] = dialog */
};
static const ProtobufCIntRange end_point_speech__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor end_point_speech__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndPointSpeech",
  "EndPointSpeech",
  "EndPointSpeech",
  "",
  sizeof(EndPointSpeech),
  1,
  end_point_speech__field_descriptors,
  end_point_speech__field_indices_by_name,
  1,  end_point_speech__number_ranges,
  (ProtobufCMessageInit) end_point_speech__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor notify_speech_state__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NotifySpeechState, state),
    &dma_speech_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify_speech_state__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange notify_speech_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dma_notify_speech_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifySpeechState",
  "NotifySpeechState",
  "NotifySpeechState",
  "",
  sizeof(NotifySpeechState),
  1,
  notify_speech_state__field_descriptors,
  notify_speech_state__field_indices_by_name,
  1,  notify_speech_state__number_ranges,
  (ProtobufCMessageInit) dma_notify_speech_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_information__field_descriptors[19] =
{
  {
    "serial_number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, serial_number),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_transports",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DeviceInformation, n_supported_transports),
    offsetof(DeviceInformation, supported_transports),
    &dma_transport__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, device_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_audio_formats",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DeviceInformation, n_supported_audio_formats),
    offsetof(DeviceInformation, supported_audio_formats),
    &dma_audio_format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "manufacturer",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, manufacturer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_version",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, firmware_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "software_version",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, software_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initiator_type",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, initiator_type),
    &initiator_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "product_id",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, product_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classic_bluetooth_mac",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, classic_bluetooth_mac),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disable_heart_beat",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, disable_heart_beat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable_advanced_security",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, enable_advanced_security),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "support_fm",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, support_fm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ota_version",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, ota_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_a2dp",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, no_a2dp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_at_command",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, no_at_command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "support_media",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, support_media),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_information__field_indices_by_name[] = {
  11,   /* field[11] = classic_bluetooth_mac */
  3,   /* field[3] = device_type */
  12,   /* field[12] = disable_heart_beat */
  13,   /* field[13] = enable_advanced_security */
  7,   /* field[7] = firmware_version */
  9,   /* field[9] = initiator_type */
  5,   /* field[5] = manufacturer */
  6,   /* field[6] = model */
  1,   /* field[1] = name */
  16,   /* field[16] = no_a2dp */
  17,   /* field[17] = no_at_command */
  15,   /* field[15] = ota_version */
  10,   /* field[10] = product_id */
  0,   /* field[0] = serial_number */
  8,   /* field[8] = software_version */
  14,   /* field[14] = support_fm */
  18,   /* field[18] = support_media */
  4,   /* field[4] = supported_audio_formats */
  2,   /* field[2] = supported_transports */
};
static const ProtobufCIntRange device_information__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 15, 12 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor dma_device_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInformation",
  "DeviceInformation",
  "DeviceInformation",
  "",
  sizeof(DeviceInformation),
  19,
  device_information__field_descriptors,
  device_information__field_indices_by_name,
  2,  device_information__number_ranges,
  (ProtobufCMessageInit) dma_device_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pair_information__field_descriptors[3] =
{
  {
    "rand",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PairInformation, rand),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PairInformation, sign),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signMethod",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PairInformation, signmethod),
    &sign_method__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pair_information__field_indices_by_name[] = {
  0,   /* field[0] = rand */
  1,   /* field[1] = sign */
  2,   /* field[2] = signMethod */
};
static const ProtobufCIntRange pair_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pair_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PairInformation",
  "PairInformation",
  "PairInformation",
  "",
  sizeof(PairInformation),
  3,
  pair_information__field_descriptors,
  pair_information__field_indices_by_name,
  1,  pair_information__number_ranges,
  (ProtobufCMessageInit) pair_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_configuration__field_descriptors[2] =
{
  {
    "needs_assistant_override",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceConfiguration, needs_assistant_override),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "needs_setup",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceConfiguration, needs_setup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_configuration__field_indices_by_name[] = {
  0,   /* field[0] = needs_assistant_override */
  1,   /* field[1] = needs_setup */
};
static const ProtobufCIntRange device_configuration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dma_device_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceConfiguration",
  "DeviceConfiguration",
  "DeviceConfiguration",
  "",
  sizeof(DeviceConfiguration),
  2,
  device_configuration__field_descriptors,
  device_configuration__field_indices_by_name,
  1,  device_configuration__number_ranges,
  (ProtobufCMessageInit) dma_device_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define get_device_information__field_descriptors NULL
#define get_device_information__field_indices_by_name NULL
#define get_device_information__number_ranges NULL
const ProtobufCMessageDescriptor dma_get_device_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetDeviceInformation",
  "GetDeviceInformation",
  "GetDeviceInformation",
  "",
  sizeof(GetDeviceInformation),
  0,
  get_device_information__field_descriptors,
  get_device_information__field_indices_by_name,
  0,  get_device_information__number_ranges,
  (ProtobufCMessageInit) dma_get_device_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define get_device_configuration__field_descriptors NULL
#define get_device_configuration__field_indices_by_name NULL
#define get_device_configuration__number_ranges NULL
const ProtobufCMessageDescriptor dma_get_device_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetDeviceConfiguration",
  "GetDeviceConfiguration",
  "GetDeviceConfiguration",
  "",
  sizeof(GetDeviceConfiguration),
  0,
  get_device_configuration__field_descriptors,
  get_device_configuration__field_indices_by_name,
  0,  get_device_configuration__number_ranges,
  (ProtobufCMessageInit) dma_get_device_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define notify_device_configuration__field_descriptors NULL
#define notify_device_configuration__field_indices_by_name NULL
#define notify_device_configuration__number_ranges NULL
const ProtobufCMessageDescriptor dma_notify_device_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifyDeviceConfiguration",
  "NotifyDeviceConfiguration",
  "NotifyDeviceConfiguration",
  "",
  sizeof(NotifyDeviceConfiguration),
  0,
  notify_device_configuration__field_descriptors,
  notify_device_configuration__field_indices_by_name,
  0,  notify_device_configuration__number_ranges,
  (ProtobufCMessageInit) dma_notify_device_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__field_descriptors[3] =
{
  {
    "feature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(State, feature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boolean",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(State, value_case),
    offsetof(State, boolean),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integer",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State, value_case),
    offsetof(State, integer),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__field_indices_by_name[] = {
  1,   /* field[1] = boolean */
  0,   /* field[0] = feature */
  2,   /* field[2] = integer */
};
static const ProtobufCIntRange state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dma_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "State",
  "State",
  "State",
  "",
  sizeof(State),
  3,
  state__field_descriptors,
  state__field_indices_by_name,
  1,  state__number_ranges,
  (ProtobufCMessageInit) dma_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_state__field_descriptors[1] =
{
  {
    "feature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetState, feature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_state__field_indices_by_name[] = {
  0,   /* field[0] = feature */
};
static const ProtobufCIntRange get_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dma_get_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetState",
  "GetState",
  "GetState",
  "",
  sizeof(GetState),
  1,
  get_state__field_descriptors,
  get_state__field_indices_by_name,
  1,  get_state__number_ranges,
  (ProtobufCMessageInit) dma_get_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_state__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SetState, state),
    &dma_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_state__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange set_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dma_set_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetState",
  "SetState",
  "SetState",
  "",
  sizeof(SetState),
  1,
  set_state__field_descriptors,
  set_state__field_indices_by_name,
  1,  set_state__number_ranges,
  (ProtobufCMessageInit) dma_set_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor synchronize_state__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SynchronizeState, state),
    &dma_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned synchronize_state__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange synchronize_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dma_synchronize_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SynchronizeState",
  "SynchronizeState",
  "SynchronizeState",
  "",
  sizeof(SynchronizeState),
  1,
  synchronize_state__field_descriptors,
  synchronize_state__field_indices_by_name,
  1,  synchronize_state__number_ranges,
  (ProtobufCMessageInit) dma_synchronize_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor forward_atcommand__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ForwardATCommand, command),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned forward_atcommand__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange forward_atcommand__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dma_forward_atcommand__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ForwardATCommand",
  "ForwardATCommand",
  "ForwardATCommand",
  "",
  sizeof(ForwardATCommand),
  1,
  forward_atcommand__field_descriptors,
  forward_atcommand__field_indices_by_name,
  1,  forward_atcommand__number_ranges,
  (ProtobufCMessageInit) dma_forward_atcommand__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor forward_test_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ForwardTestCommand, command),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned forward_test_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange forward_test_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor forward_test_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ForwardTestCommand",
  "ForwardTestCommand",
  "ForwardTestCommand",
  "",
  sizeof(ForwardTestCommand),
  1,
  forward_test_command__field_descriptors,
  forward_test_command__field_indices_by_name,
  1,  forward_test_command__number_ranges,
  (ProtobufCMessageInit) forward_test_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor issue_media_control__field_descriptors[2] =
{
  {
    "control",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IssueMediaControl, control),
    &dma_media_control__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "volume",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IssueMediaControl, volume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned issue_media_control__field_indices_by_name[] = {
  0,   /* field[0] = control */
  1,   /* field[1] = volume */
};
static const ProtobufCIntRange issue_media_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dma_issue_media_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IssueMediaControl",
  "IssueMediaControl",
  "IssueMediaControl",
  "",
  sizeof(IssueMediaControl),
  2,
  issue_media_control__field_descriptors,
  issue_media_control__field_indices_by_name,
  1,  issue_media_control__number_ranges,
  (ProtobufCMessageInit) dma_issue_media_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue transport__enum_values_by_number[3] =
{
  { "BLUETOOTH_LOW_ENERGY", "TRANSPORT__BLUETOOTH_LOW_ENERGY", 0 },
  { "BLUETOOTH_RFCOMM", "TRANSPORT__BLUETOOTH_RFCOMM", 1 },
  { "BLUETOOTH_IAP", "TRANSPORT__BLUETOOTH_IAP", 2 },
};
static const ProtobufCIntRange transport__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex transport__enum_values_by_name[3] =
{
  { "BLUETOOTH_IAP", 2 },
  { "BLUETOOTH_LOW_ENERGY", 0 },
  { "BLUETOOTH_RFCOMM", 1 },
};
const ProtobufCEnumDescriptor dma_transport__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Transport",
  "Transport",
  "Transport",
  "",
  3,
  transport__enum_values_by_number,
  3,
  transport__enum_values_by_name,
  1,
  transport__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue error_code__enum_values_by_number[10] =
{
  { "SUCCESS", "ERROR_CODE__SUCCESS", 0 },
  { "UNKNOWN", "ERROR_CODE__UNKNOWN", 1 },
  { "INTERNAL", "ERROR_CODE__INTERNAL", 2 },
  { "UNSUPPORTED", "ERROR_CODE__UNSUPPORTED", 3 },
  { "USER_CANCELLED", "ERROR_CODE__USER_CANCELLED", 4 },
  { "NOT_FOUND", "ERROR_CODE__NOT_FOUND", 5 },
  { "INVALID", "ERROR_CODE__INVALID", 6 },
  { "BUSY", "ERROR_CODE__BUSY", 7 },
  { "NOT_IN_PAIR_MODE", "ERROR_CODE__NOT_IN_PAIR_MODE", 8 },
  { "SIGN_VERIFY_FAIL", "ERROR_CODE__SIGN_VERIFY_FAIL", 9 },
};
static const ProtobufCIntRange error_code__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex error_code__enum_values_by_name[10] =
{
  { "BUSY", 7 },
  { "INTERNAL", 2 },
  { "INVALID", 6 },
  { "NOT_FOUND", 5 },
  { "NOT_IN_PAIR_MODE", 8 },
  { "SIGN_VERIFY_FAIL", 9 },
  { "SUCCESS", 0 },
  { "UNKNOWN", 1 },
  { "UNSUPPORTED", 3 },
  { "USER_CANCELLED", 4 },
};
const ProtobufCEnumDescriptor dma_error_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ErrorCode",
  "ErrorCode",
  "ErrorCode",
  "",
  10,
  error_code__enum_values_by_number,
  10,
  error_code__enum_values_by_name,
  1,
  error_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue command__enum_values_by_number[30] =
{
  { "PROVIDE_SPEECH", "COMMAND__PROVIDE_SPEECH", 0 },
  { "PROVIDE_SPEECH_ACK", "COMMAND__PROVIDE_SPEECH_ACK", 1 },
  { "START_SPEECH", "COMMAND__START_SPEECH", 2 },
  { "START_SPEECH_ACK", "COMMAND__START_SPEECH_ACK", 3 },
  { "STOP_SPEECH", "COMMAND__STOP_SPEECH", 4 },
  { "STOP_SPEECH_ACK", "COMMAND__STOP_SPEECH_ACK", 5 },
  { "END_POINT_SPEECH", "COMMAND__END_POINT_SPEECH", 6 },
  { "END_POINT_SPEECH_ACK", "COMMAND__END_POINT_SPEECH_ACK", 7 },
  { "NOTIFY_SPEECH_STATE", "COMMAND__NOTIFY_SPEECH_STATE", 8 },
  { "NOTIFY_SPEECH_STATE_ACK", "COMMAND__NOTIFY_SPEECH_STATE_ACK", 9 },
  { "GET_DEVICE_INFORMATION", "COMMAND__GET_DEVICE_INFORMATION", 20 },
  { "GET_DEVICE_INFORMATION_ACK", "COMMAND__GET_DEVICE_INFORMATION_ACK", 21 },
  { "GET_DEVICE_CONFIGURATION", "COMMAND__GET_DEVICE_CONFIGURATION", 22 },
  { "GET_DEVICE_CONFIGURATION_ACK", "COMMAND__GET_DEVICE_CONFIGURATION_ACK", 23 },
  { "NOTIFY_DEVICE_CONFIGURATION", "COMMAND__NOTIFY_DEVICE_CONFIGURATION", 24 },
  { "NOTIFY_DEVICE_CONFIGURATION_ACK", "COMMAND__NOTIFY_DEVICE_CONFIGURATION_ACK", 25 },
  { "PAIR", "COMMAND__PAIR", 26 },
  { "PAIR_ACK", "COMMAND__PAIR_ACK", 27 },
  { "GET_STATE", "COMMAND__GET_STATE", 30 },
  { "GET_STATE_ACK", "COMMAND__GET_STATE_ACK", 31 },
  { "SET_STATE", "COMMAND__SET_STATE", 32 },
  { "SET_STATE_ACK", "COMMAND__SET_STATE_ACK", 33 },
  { "SYNCHRONIZE_STATE", "COMMAND__SYNCHRONIZE_STATE", 34 },
  { "SYNCHRONIZE_STATE_ACK", "COMMAND__SYNCHRONIZE_STATE_ACK", 35 },
  { "FORWARD_AT_COMMAND", "COMMAND__FORWARD_AT_COMMAND", 40 },
  { "FORWARD_AT_COMMAND_ACK", "COMMAND__FORWARD_AT_COMMAND_ACK", 41 },
  { "FORWARD_TEST_COMMAND", "COMMAND__FORWARD_TEST_COMMAND", 42 },
  { "FORWARD_TEST_COMMAND_ACK", "COMMAND__FORWARD_TEST_COMMAND_ACK", 43 },
  { "ISSUE_MEDIA_CONTROL", "COMMAND__ISSUE_MEDIA_CONTROL", 44 },
  { "ISSUE_MEDIA_CONTROL_ACK", "COMMAND__ISSUE_MEDIA_CONTROL_ACK", 45 },
};
static const ProtobufCIntRange command__value_ranges[] = {
{0, 0},{20, 10},{30, 18},{40, 24},{0, 30}
};
static const ProtobufCEnumValueIndex command__enum_values_by_name[30] =
{
  { "END_POINT_SPEECH", 6 },
  { "END_POINT_SPEECH_ACK", 7 },
  { "FORWARD_AT_COMMAND", 24 },
  { "FORWARD_AT_COMMAND_ACK", 25 },
  { "FORWARD_TEST_COMMAND", 26 },
  { "FORWARD_TEST_COMMAND_ACK", 27 },
  { "GET_DEVICE_CONFIGURATION", 12 },
  { "GET_DEVICE_CONFIGURATION_ACK", 13 },
  { "GET_DEVICE_INFORMATION", 10 },
  { "GET_DEVICE_INFORMATION_ACK", 11 },
  { "GET_STATE", 18 },
  { "GET_STATE_ACK", 19 },
  { "ISSUE_MEDIA_CONTROL", 28 },
  { "ISSUE_MEDIA_CONTROL_ACK", 29 },
  { "NOTIFY_DEVICE_CONFIGURATION", 14 },
  { "NOTIFY_DEVICE_CONFIGURATION_ACK", 15 },
  { "NOTIFY_SPEECH_STATE", 8 },
  { "NOTIFY_SPEECH_STATE_ACK", 9 },
  { "PAIR", 16 },
  { "PAIR_ACK", 17 },
  { "PROVIDE_SPEECH", 0 },
  { "PROVIDE_SPEECH_ACK", 1 },
  { "SET_STATE", 20 },
  { "SET_STATE_ACK", 21 },
  { "START_SPEECH", 2 },
  { "START_SPEECH_ACK", 3 },
  { "STOP_SPEECH", 4 },
  { "STOP_SPEECH_ACK", 5 },
  { "SYNCHRONIZE_STATE", 22 },
  { "SYNCHRONIZE_STATE_ACK", 23 },
};
const ProtobufCEnumDescriptor dma_command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Command",
  "Command",
  "Command",
  "",
  30,
  command__enum_values_by_number,
  30,
  command__enum_values_by_name,
  4,
  command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue audio_source__enum_values_by_number[1] =
{
  { "STREAM", "AUDIO_SOURCE__STREAM", 0 },
};
static const ProtobufCIntRange audio_source__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex audio_source__enum_values_by_name[1] =
{
  { "STREAM", 0 },
};
const ProtobufCEnumDescriptor dma_audio_source__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AudioSource",
  "AudioSource",
  "AudioSource",
  "",
  1,
  audio_source__enum_values_by_number,
  1,
  audio_source__enum_values_by_name,
  1,
  audio_source__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue audio_profile__enum_values_by_number[3] =
{
  { "CLOSE_TALK", "AUDIO_PROFILE__CLOSE_TALK", 0 },
  { "NEAR_FIELD", "AUDIO_PROFILE__NEAR_FIELD", 1 },
  { "FAR_FIELD", "AUDIO_PROFILE__FAR_FIELD", 2 },
};
static const ProtobufCIntRange audio_profile__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex audio_profile__enum_values_by_name[3] =
{
  { "CLOSE_TALK", 0 },
  { "FAR_FIELD", 2 },
  { "NEAR_FIELD", 1 },
};
const ProtobufCEnumDescriptor dma_audio_profile__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AudioProfile",
  "AudioProfile",
  "AudioProfile",
  "",
  3,
  audio_profile__enum_values_by_number,
  3,
  audio_profile__enum_values_by_name,
  1,
  audio_profile__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue audio_format__enum_values_by_number[6] =
{
  { "PCM_L16_16KHZ_MONO", "AUDIO_FORMAT__PCM_L16_16KHZ_MONO", 0 },
  { "OPUS_16KHZ_32KBPS_CBR_0_20MS", "AUDIO_FORMAT__OPUS_16KHZ_32KBPS_CBR_0_20MS", 1 },
  { "OPUS_16KHZ_16KBPS_CBR_0_20MS", "AUDIO_FORMAT__OPUS_16KHZ_16KBPS_CBR_0_20MS", 2 },
  { "MSBC", "AUDIO_FORMAT__MSBC", 3 },
  { "SPEEX_16KHZ_16KBPS", "AUDIO_FORMAT__SPEEX_16KHZ_16KBPS", 4 },
  { "SBC_16KHZ_MONO_16KBPS_28BITPOOL_16NUMBLOCKS_8SUBBANDS_SNR", "AUDIO_FORMAT__SBC_16KHZ_MONO_16KBPS_28BITPOOL_16NUMBLOCKS_8SUBBANDS_SNR", 5 },
};
static const ProtobufCIntRange audio_format__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex audio_format__enum_values_by_name[6] =
{
  { "MSBC", 3 },
  { "OPUS_16KHZ_16KBPS_CBR_0_20MS", 2 },
  { "OPUS_16KHZ_32KBPS_CBR_0_20MS", 1 },
  { "PCM_L16_16KHZ_MONO", 0 },
  { "SBC_16KHZ_MONO_16KBPS_28BITPOOL_16NUMBLOCKS_8SUBBANDS_SNR", 5 },
  { "SPEEX_16KHZ_16KBPS", 4 },
};
const ProtobufCEnumDescriptor dma_audio_format__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AudioFormat",
  "AudioFormat",
  "AudioFormat",
  "",
  6,
  audio_format__enum_values_by_number,
  6,
  audio_format__enum_values_by_name,
  1,
  audio_format__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue speech_state__enum_values_by_number[4] =
{
  { "IDLE", "SPEECH_STATE__IDLE", 0 },
  { "LISTENING", "SPEECH_STATE__LISTENING", 1 },
  { "PROCESSING", "SPEECH_STATE__PROCESSING", 2 },
  { "SPEAKING", "SPEECH_STATE__SPEAKING", 3 },
};
static const ProtobufCIntRange speech_state__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex speech_state__enum_values_by_name[4] =
{
  { "IDLE", 0 },
  { "LISTENING", 1 },
  { "PROCESSING", 2 },
  { "SPEAKING", 3 },
};
const ProtobufCEnumDescriptor dma_speech_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SpeechState",
  "SpeechState",
  "SpeechState",
  "",
  4,
  speech_state__enum_values_by_number,
  4,
  speech_state__enum_values_by_name,
  1,
  speech_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue initiator_type__enum_values_by_number[4] =
{
  { "PRESS_AND_HOLD", "INITIATOR_TYPE__PRESS_AND_HOLD", 0 },
  { "TAP", "INITIATOR_TYPE__TAP", 1 },
  { "PHONE_WAKEUP", "INITIATOR_TYPE__PHONE_WAKEUP", 2 },
  { "WAIT_FOLLOW_WAKEUP", "INITIATOR_TYPE__WAIT_FOLLOW_WAKEUP", 3 },
};
static const ProtobufCIntRange initiator_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex initiator_type__enum_values_by_name[4] =
{
  { "PHONE_WAKEUP", 2 },
  { "PRESS_AND_HOLD", 0 },
  { "TAP", 1 },
  { "WAIT_FOLLOW_WAKEUP", 3 },
};
const ProtobufCEnumDescriptor initiator_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "InitiatorType",
  "InitiatorType",
  "InitiatorType",
  "",
  4,
  initiator_type__enum_values_by_number,
  4,
  initiator_type__enum_values_by_name,
  1,
  initiator_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue sign_method__enum_values_by_number[3] =
{
  { "SHA256", "SIGN_METHOD__SHA256", 0 },
  { "SHA1", "SIGN_METHOD__SHA1", 1 },
  { "MD5SUM", "SIGN_METHOD__MD5SUM", 2 },
};
static const ProtobufCIntRange sign_method__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex sign_method__enum_values_by_name[3] =
{
  { "MD5SUM", 2 },
  { "SHA1", 1 },
  { "SHA256", 0 },
};
const ProtobufCEnumDescriptor sign_method__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SignMethod",
  "SignMethod",
  "SignMethod",
  "",
  3,
  sign_method__enum_values_by_number,
  3,
  sign_method__enum_values_by_name,
  1,
  sign_method__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue media_control__enum_values_by_number[5] =
{
  { "PLAY", "MEDIA_CONTROL__PLAY", 0 },
  { "PAUSE", "MEDIA_CONTROL__PAUSE", 1 },
  { "NEXT", "MEDIA_CONTROL__NEXT", 2 },
  { "PREVIOUS", "MEDIA_CONTROL__PREVIOUS", 3 },
  { "ABSOLUTE_VOLUME", "MEDIA_CONTROL__ABSOLUTE_VOLUME", 4 },
};
static const ProtobufCIntRange media_control__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex media_control__enum_values_by_name[5] =
{
  { "ABSOLUTE_VOLUME", 4 },
  { "NEXT", 2 },
  { "PAUSE", 1 },
  { "PLAY", 0 },
  { "PREVIOUS", 3 },
};
const ProtobufCEnumDescriptor dma_media_control__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MediaControl",
  "MediaControl",
  "MediaControl",
  "",
  5,
  media_control__enum_values_by_number,
  5,
  media_control__enum_values_by_name,
  1,
  media_control__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
